[package]
name = "ggfm-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
getrandom.workspace = true
ggfm-domain = { path = "../domain" }
ggfm-transport-http = { path = "../transport-http" }
hex.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true

