use std::{collections::BTreeSet, env, fs, path::PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Document {
    calls: Vec<Call>,
}

#[derive(Deserialize)]
struct Call {
    name: String,
    category: String,
    class: String,
}

fn rust_variant(name: &str) -> String {
    let mut result = String::new();
    let mut uppercase_next = true;
    for character in name.chars() {
        if !character.is_ascii_alphanumeric() {
            uppercase_next = true;
            continue;
        }
        if uppercase_next {
            result.push(character.to_ascii_uppercase());
            uppercase_next = false;
        } else {
            result.push(character);
        }
    }
    if result.as_bytes().first().is_some_and(u8::is_ascii_digit) {
        result.insert_str(0, "Rpc");
    }
    result
}

fn main() {
    let schema_path = PathBuf::from("schema/protocol.json");
    println!("cargo:rerun-if-changed={}", schema_path.display());
    let source = fs::read_to_string(&schema_path).expect("read audited protocol schema");
    let document: Document = serde_json::from_str(&source).expect("parse audited protocol schema");
    assert_eq!(document.calls.len(), 127, "audited RPC count changed");

    let mut names = BTreeSet::new();
    let mut variants = BTreeSet::new();
    for call in &document.calls {
        assert!(
            names.insert(call.name.clone()),
            "duplicate RPC {}",
            call.name
        );
        assert!(
            variants.insert(rust_variant(&call.name)),
            "RPC Rust variant collision for {}",
            call.name
        );
    }

    let mut generated = String::from(
        "// @generated by crates/protocol/build.rs from schema/protocol.json.\n\
         // Do not edit this file or add gameplay behavior here.\n\
         #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\n\
         pub enum RpcName {\n",
    );
    for call in &document.calls {
        generated.push_str(&format!("    {},\n", rust_variant(&call.name)));
    }
    generated.push_str("}\n\nimpl RpcName {\n");
    generated.push_str("    pub const ALL: [Self; 127] = [\n");
    for call in &document.calls {
        generated.push_str(&format!("        Self::{},\n", rust_variant(&call.name)));
    }
    generated.push_str("    ];\n\n");
    generated.push_str("    pub const fn as_str(self) -> &'static str { match self {\n");
    for call in &document.calls {
        generated.push_str(&format!(
            "        Self::{} => {:?},\n",
            rust_variant(&call.name),
            call.name
        ));
    }
    generated.push_str("    }}\n\n");
    generated.push_str("    pub const fn category(self) -> &'static str { match self {\n");
    for call in &document.calls {
        generated.push_str(&format!(
            "        Self::{} => {:?},\n",
            rust_variant(&call.name),
            call.category
        ));
    }
    generated.push_str("    }}\n\n");
    generated.push_str("    pub const fn class(self) -> RpcClass { match self {\n");
    for call in &document.calls {
        let class = match call.class.as_str() {
            "active" => "RpcClass::Active",
            "transport-only" => "RpcClass::TransportOnly",
            "dto-only" => "RpcClass::DtoOnly",
            other => panic!("unknown RPC class {other}"),
        };
        generated.push_str(&format!(
            "        Self::{} => {},\n",
            rust_variant(&call.name),
            class
        ));
    }
    generated.push_str("    }}\n\n");
    generated
        .push_str("    pub fn from_wire_name(value: &str) -> Option<Self> { Some(match value {\n");
    for call in &document.calls {
        generated.push_str(&format!(
            "        {:?} => Self::{},\n",
            call.name,
            rust_variant(&call.name)
        ));
    }
    generated.push_str("        _ => return None,\n    })}\n}\n");

    let output = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("rpc_names.rs");
    fs::write(output, generated).expect("write generated typed RPC registry");
}
